tap 'homebrew/cask'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle'
tap 'homebrew/core'

brew 'ack'
brew 'autojump'
brew 'bash'
brew 'gh'
brew 'git'
brew 'gpg'
brew 'mas'
brew 'node'
brew 'nvm'
brew 'rbenv'
brew 'readline'
brew 'the_silver_searcher'
brew 'vim'

cask '1password'
cask 'alfred'
cask 'bartender'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'hazel'
cask 'imageoptim'
cask 'iterm2'
cask 'karabiner-elements'
cask 'key-codes'
cask 'keyboard-maestro'
cask 'ksdiff'
cask 'moom'
cask 'musescore'
cask 'numi'
cask 'paw'
cask 'sketch'
cask 'spotify'
cask 'visual-studio-code'

mas 'ColorSnapper2', id: 969418666
mas 'Deliveries', id: 924726344
mas 'Keynote', id: 409183694
mas 'Kindle', id: 405399194
mas 'Name Mangler', id: 603637384
mas 'Numbers', id: 409203825
mas 'Pages', id: 409201541
mas 'Paste Plain Text', id: 1407015686
mas 'Pixelmator Pro', id: 1289583905
mas 'iA Writer', id: 775737590
