tap 'oven-sh/bun'

brew 'ack'
brew 'autojump'
brew 'bash'
brew 'bash-completion@2'
brew 'bun'
brew 'fnm'
brew 'gh'
brew 'git'
brew 'gpg'
brew 'mas'
brew 'pyenv'
brew 'rbenv'
brew 'readline'
brew 'starship'
brew 'the_silver_searcher'
brew 'vim'
brew 'zsh'

cask '1password'
cask 'alfred'
cask 'bartender'
cask 'colour-contrast-analyser'
cask 'comfyui'
cask 'cursor'
cask 'figma'
cask 'firefox'
cask 'google-chrome'
cask 'hazel'
cask 'imageoptim'
cask 'iterm2'
cask 'kaleidoscope'
cask 'karabiner-elements'
cask 'key-codes'
cask 'keyboard-maestro'
cask 'microsoft-edge'
cask 'moom'
cask 'numi'
cask 'rapidapi'
cask 'spotify'
cask 'visual-studio-code'

mas 'ColorSnapper2', id: 969418666
mas 'LanguageTool', id: 1534275760
mas 'Name Mangler', id: 603637384
mas 'Paste Plain Text', id: 1407015686
mas 'Slack', id: 803453959
mas 'The Unarchiver', id: 425424353
mas 'Xcode', id: 497799835
