[character]
error_symbol = "[>](red)"
success_symbol = ">"

[cmd_duration]
disabled = true

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
home_symbol = "john"
style = ""

[git_branch]
format = ":[$branch]($style) "
style = "bold"

[bun]
disabled = false
style = "fg:yellow"
symbol="Bun "

[nodejs]
disabled = false
style = "fg:yellow"
symbol = "Node "

[package]
disabled = true

[python]
disabled = true
style = "fg:green"
symbol = "Python "

[ruby]
disabled = true
style = "fg:red"
symbol = "Ruby "

[shell]
bash_indicator = "bash"
disabled = false
zsh_indicator = "zsh"
