[character]
error_symbol = "[▶︎](red)"
success_symbol = "[▶︎](green)"

[cmd_duration]
disabled = true

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
home_symbol = "john ~"

[git_branch]
format =":[$branch]($style) "

[nodejs]
style = "fg:yellow"
symbol = "Node "

[package]
disabled = true

[python]
style = "fg:green"
symbol = "Python "

[ruby]
style = "fg:red"
symbol = "Ruby "

[vagrant]
disabled = true
