FONTS_TO_DELETE=(
  'Al Nile.ttc'
  'Al Tarikh.ttc'
  'AlBayan.ttc'
  'AmericanTypewriter.ttc'
  'Apple Chancery.ttf'
  'AppleGothic.ttf'
  'AppleMyungjo.ttf'
  'Arial Black.ttf'
  'Arial Narrow Bold Italic.ttf'
  'Arial Narrow Bold.ttf'
  'Arial Narrow Italic.ttf'
  'Arial Narrow.ttf'
  'Arial Rounded Bold.ttf'
  'Arial Unicode.ttf'
  'Ayuthaya.ttf'
  'Baghdad.ttc'
  'Bangla MN.ttc'
  'Bangla Sangam MN.ttc'
  'Baoli.ttc'
  'Beirut.ttc'
  'Bradley Hand Bold.ttf'
  'Brush Script.ttf'
  'Chalkboard.ttc'
  'ChalkboardSE.ttc'
  'Chalkduster.ttf'
  'Charter.ttc'
  'Cochin.ttc'
  'Copperplate.ttc'
  'Corsiva.ttc'
  'Damascus.ttc'
  'DecoTypeNaskh.ttc'
  'Devanagari Sangam MN.ttc'
  'DevanagariMT.ttc'
  'DIN Alternate Bold.ttf'
  'DIN Condensed Bold.ttf'
  'Diwan Kufi.ttc'
  'Diwan Thuluth.ttf'
  'EuphemiaCAS.ttc'
  'Farah.ttc'
  'Farisi.ttf'
  'Gujarati Sangam MN.ttc'
  'GujaratiMT.ttc'
  'Gungseouche.ttf'
  'Gurmukhi MN.ttc'
  'Gurmukhi Sangam MN.ttc'
  'Gurmukhi.ttf'
  'Hannotate.ttc'
  'Hanzipen.ttc'
  'HeadlineA.ttf'
  'Herculanum.ttf'
  'Impact.ttf'
  'InaiMathi.ttf'
  'Iowan Old Style.ttc'
  'ITFDevanagari.ttc'
  'Kailasa.ttc'
  'Kaiti.ttc'
  'Kannada MN.ttc'
  'Kannada Sangam MN.ttc'
  'Kefa.ttc'
  'Khmer MN.ttc'
  'Khmer Sangam MN.ttf'
  'Klee.ttc'
  'Kokonor.ttf'
  'Krungthep.ttf'
  'KufiStandardGK.ttc'
  'Lantinghei.ttc'
  'Lao MN.ttc'
  'Lao Sangam MN.ttf'
  'Libian.ttc'
  'Luminari.ttf'
  'Malayalam MN.ttc'
  'Malayalam Sangam MN.ttc'
  'Marion.ttc'
  'Microsoft Sans Serif.ttf'
  'Mishafi Gold.ttf'
  'Mishafi.ttf'
  'Mshtakan.ttc'
  'Muna.ttc'
  'Myanmar MN.ttc'
  'Myanmar Sangam MN.ttc'
  'Nadeem.ttc'
  'NanumGothic.ttc'
  'NanumMyeongjo.ttc'
  'NewPeninimMT.ttc'
  'NISC18030.ttf'
  'Oriya MN.ttc'
  'Oriya Sangam MN.ttc'
  'Osaka.ttf'
  'OsakaMono.ttf'
  'Papyrus.ttc'
  'PCmyoungjo.ttf'
  'Phosphate.ttc'
  'Pilgiche.ttf'
  'PlantagenetCherokee.ttf'
  'PTMono.ttc'
  'PTSans.ttc'
  'PTSerif.ttc'
  'PTSerifCaption.ttc'
  'Raanana.ttc'
  'Sana.ttc'
  'Sathu.ttf'
  'Savoye LET.ttc'
  'Seravek.ttc'
  'Shree714.ttc'
  'SignPainter.otf'
  'Silom.ttf'
  'Sinhala MN.ttc'
  'Sinhala Sangam MN.ttc'
  'Skia.ttf'
  'SnellRoundhand.ttc'
  'Songti.ttc'
  'SukhumvitSet.ttc'
  'STIXGeneral.otf'
  'STIXGeneralBol.otf'
  'STIXGeneralBolIta.otf'
  'STIXGeneralItalic.otf'
  'STIXIntDBol.otf'
  'STIXIntDReg.otf'
  'STIXIntSmBol.otf'
  'STIXIntSmReg.otf'
  'STIXIntUpBol.otf'
  'STIXIntUpDBol.otf'
  'STIXIntUpDReg.otf'
  'STIXIntUpReg.otf'
  'STIXIntUpSmBol.otf'
  'STIXIntUpSmReg.otf'
  'STIXNonUni.otf'
  'STIXNonUniBol.otf'
  'STIXNonUniBolIta.otf'
  'STIXNonUniIta.otf'
  'STIXSizFiveSymReg.otf'
  'STIXSizFourSymBol.otf'
  'STIXSizFourSymReg.otf'
  'STIXSizOneSymBol.otf'
  'STIXSizOneSymReg.otf'
  'STIXSizThreeSymBol.otf'
  'STIXSizThreeSymReg.otf'
  'STIXSizTwoSymBol.otf'
  'STIXSizTwoSymReg.otf'
  'STIXVar.otf'
  'STIXVarBol.otf'
  'Tamil MN.ttc'
  'Tamil Sangam MN.ttc'
  'Telugu MN.ttc'
  'Telugu Sangam MN.ttc'
  'Trattatello.ttf'
  'Trebuchet MS Bold Italic.ttf'
  'Trebuchet MS Bold.ttf'
  'Trebuchet MS Italic.ttf'
  'Trebuchet MS.ttf'
  'TsukushiAMaruGothic.ttc'
  'TsukushiBMaruGothic.ttc'
  'Waseem.ttc'
  'WawaSC-Regular.otf'
  'WawaTC-Regular.otf'
  'Webdings.ttf'
  'WeibeiSC-Bold.otf'
  'WeibeiTC-Bold.otf'
  'Wingdings 2.ttf'
  'Wingdings 3.ttf'
  'Wingdings.ttf'
  'Xingkai.ttc'
  'Yu Gothic Bold.otf'
  'Yu Gothic Medium.otf'
  'Yuanti.ttc'
  'YuMincho.ttc'
  'YuppySC-Regular.otf'
  'YuppyTC-Regular.otf'
  'Zapfino.ttf'
  'ヒラギノ丸ゴ ProN W4.ttc'
  '儷宋 Pro.ttf'
  '儷黑 Pro.ttf'
  '华文仿宋.ttf'
  '华文细黑.ttf'
  '华文黑体.ttf'
)

for font in "${FONTS_TO_DELETE[@]}"; do
  sudo rm -f "/Library/Fonts/$font"
done
