# ----------------------------------------------------
#
#   Zsh
#   -> User-defined Zsh settings
#
# ----------------------------------------------------

# ----------------------------------------------------
#   Imports
# ----------------------------------------------------

# ----- Shared ----- #

. ~/.dotfiles/shell/variables
. ~/.dotfiles/shell/aliases
. ~/.dotfiles/shell/config
. ~/.dotfiles/shell/functions

# ----- Zsh ----- #

. ~/.dotfiles/zsh/config
. ~/.dotfiles/zsh/prompt
