# ----------------------------------------------------
#
#   Bash
#   -> User-defined Bash settings
#
# ----------------------------------------------------

# ----------------------------------------------------
#   Imports
# ----------------------------------------------------

# ----- Initial ----- #

. ~/.dotfiles/bash/init

# ----- Shared ----- #

. ~/.dotfiles/shell/variables
. ~/.dotfiles/shell/aliases
. ~/.dotfiles/shell/config
. ~/.dotfiles/shell/functions/dependencies
. ~/.dotfiles/shell/functions/general

# ----- Bash ----- #

. ~/.dotfiles/bash/aliases
. ~/.dotfiles/bash/config
. ~/.dotfiles/bash/prompt

# ----- Completion ----- #

. ~/.dotfiles/shell/completion
